server:
  servlet:
    context-path: /

spring:
  thymeleaf:
    cache: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://120.24.169.221:3306/blog?characterEncoding=utf-8&useSSL=false&serverTimezone=Hongkong
    username: root
    password: Ue!p41SQL

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.community.entity
  configuration:
    use-generated-keys: true
    # 启用自动增长组件
    map-underscore-to-camel-case: true
    # 自动匹配驼峰和_命名方式